# Generated by Django 4.0.4 on 2022-04-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CountryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table2',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Table5',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Table1',
            new_name='MainTable',
        ),
        migrations.RenameModel(
            old_name='Table6',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Country',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='State',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='City',
            new_name='State',
        ),
    ]
